group: edge
dist: trusty
language: java
jsdk: oraclejdk8
install: true
before_install:
#  - nvm install 7
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt update
  - sudo apt install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
script:
  - gradle clean build
  - gradle yarn_lint
  - gradle yarn_test
  - gradle yarn_ghpages
after_script:
  - if [ -f web/npm-debug.log ]; then cat web/npm-debug.log; fi
cache:
  directories:
    - node_modules
